#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgresql-config
#  namespace: ers
#data:
#  POSTGRES_DB: postgres
#  POSTGRES_USER: postgres
#  POSTGRES_PASSWORD: example

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
  namespace: ers
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  hostPath:
    path: '/mnt/data'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql 
  namespace: ers
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      storageClassName: 
      containers:
      - name: postgresql-pv-volume
        image: postgres:12.8
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: ApplicationDbErrorReporting
        envFrom:
        - secretRef:
            name: postgres-secrets
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/
            name: ers-sql
      volumes:
        - name: ers-sql
          configMap:
            name: ers-sql
