---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-ext
  labels:
    app: kafka-app
  namespace: maroda-test
spec:
  type: NodePort
  ports:
  - port: 30092
    name: external
    protocol: TCP
    targetPort: 30092
    nodePort: 30092
  selector:
    app: kafka-app
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
  namespace: maroda-test
spec:
  selector:
    app: kafka-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

