---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
  namespace: kafka-kraft
spec:
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30092
  selector:
    app: kafka-app
