#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgresql-config
#  namespace: dunedaqers
#data:
#  POSTGRES_DB: postgres
#  POSTGRES_USER: postgres
#  POSTGRES_PASSWORD: example

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
  namespace: dunedaqers
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 10Gi
  hostPath:
    path: '/mnt/data'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql 
  namespace: dunedaqers
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      storageClassName: 
      containers:
      - name: postgresql-pv-volume
        image: postgres:11.12
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        envFrom:
        - secretRef:
            name: postgres-secrets

