---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgresql
  namespace: dunedaqers
spec:
  clusterIP: None
  ports:
    - name: '5432'
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql
