---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgresql
  namespace: dunedaqers
spec:
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    targetPort: postgres-svc
    nodePort: 30432
  selector:
    app: postgresql
