apiVersion: v1
kind: Service
metadata:
  namespace: daqconfig
  name: mongodb-svc-ext
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      name: external
      protocol: TCP
      nodePort: 31007
  selector:
    app: mongodb

