apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express
  name: mongo-express
  namespace: daqconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-express
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        env:
        - name: ME_CONFIG_OPTIONS_NO_DELETE
          value: "true"
        - name: ME_CONFIG_OPTIONS_READONLY
          value: "true"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-svc-ext"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-root
              key: password
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-root
              key: user
---
apiVersion: v1
kind: Service
metadata:
  namespace: daqconfig
  name: mongo-express-ext-svc
  labels:
    app: mongo-express-ext-svc
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      name: external
      protocol: TCP
      nodePort: 31012
  selector:
    app: mongo-express
