apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-db
  namespace: daqconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - image: mongo
        name: mongo
        args: ["--dbpath","/data/db"]
        env:
        - name: mongo-db_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: daqconfig-secrets
              key: username
        - name: mongo-db_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: daqconfig-secrets
              key: password
      #   volumeMounts:
      #   - name: mongo-data-dir
      #     mountPath: /data/db
      # volumes:
      # - name: mongo-data-dir
      #   persistentVolumeClaim:
      #     claimName: daqconfig-mongo-data
