---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  labels:
    app: mongo-db
  namespace: daqconfig
spec:
  selector:
    app: mongo-db
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
