apiVersion: v1
kind: Service
metadata:
  namespace: daqconfig
  name: mongo-db-svc-ext
  labels:
    app: mongo-db
spec:
  type: NodePort
  ports:
    - port: 27017
      name: exteral
      protocol: TCP
      targetPort: 27017
      nodePort: 31007
  selector:
    app: mongo-db

