apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: daqconfig
  labels:
    type: local
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
