apiVersion: apps/v1
kind: Deployment
metadata:
  name: minidaq
  namespace: default
spec:
  selector:
    matchLabels:
      app: minidaq
  replicas: 1
  template:
    metadata:
      labels:
        app: minidaq
    spec:
      containers:
      - name: sl7
        image: dunedaq/sl7:latest # yes, this image only has latest tages
        command: [ "sleep", "Infinity" ]
        volumeMounts:
        - mountPath: "/cvmfs/dunedaq.opensciencegrid.org"
          name: dunedaq
      volumes:
      - name: dunedaq
        persistentVolumeClaim:
          claimName: dunedaq.opensciencegrid.org
