---
apiVersion: v1  
kind: Service  
metadata:  
  name: influxdb-svc-ext
  labels:
    app: influxdb
  namespace: monitoring
spec:
  type: NodePort
  selector:  
    app: influxdb  
  ports:  
  - protocol: TCP  
    port: 8086  
    targetPort: 8086
    nodePort: 31002
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
