apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2influx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: dunedaq/pocket-opmon-microservice:1.0
        name: kafka2influx
