apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2influx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2influx
  template:
    metadata:
      labels:
        app: kafka2influx
    spec:
      containers:
      - image: dunedaq/pocket-opmon-microservice:1.0
        name: kafka2influx
        command: ["/bin/bash"]
        args: ["-c", "python3 /kafka-to-influx.py --kafka-address kafka-svc.kafka-kraft --kafka-port 9092 --influxdb-address influxdb-svc.monitoring --influxdb-port 8086"]
