apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqmbackend
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: dqmbackend
  replicas: 1
  template:
    metadata:
      labels:
        app: dqmbackend
    spec:
      volumes:
        - name: dqm-db
          emptyDir: {}
        - name: dqm-results
          emptyDir: {}
      containers:
      - name: dqmbackend
        image: dunedaq/pocket-dqmdjango:0.3.2
        ports:
        - containerPort: 8000
        env:
        - name: USERNAME
          value: "foo"
        - name: PASSWORD
          value: "bar" 
        - name: ALLOWED_HOSTS
          value: "baz"
        - name: PATH_DATABASE
          value: "/mnt/data/Database"
        - name: PATH_DATABASE_RESULTS
          value: "/mnt/data/Database-results"
        volumeMounts:
        - mountPath: "/mnt/data/Database"
          name: dqm-db
        - mountPath: "/mnt/data/Database-results"
          name: dqm-results

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqmredis
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: dqmredis
  replicas: 1
  template:
    metadata:
      labels:
        app: dqmredis
    spec:
      volumes:
        - name: dqm-shared
          emptyDir: {}
      containers:
      - name: dqmredis
        image: redis:4
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: dqm-svc
  labels:
    app: dqmbackend
  namespace: dqm
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 30081
  selector:
    app: dqmbackend
