apiVersion: v1
kind: PersistentVolume
metadata:
  name: dqm-db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /scratch/dqm-db/Database

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dqm-results
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /scratch/dqm-db/Database-results/
