apiVersion: apps/v1
kind: Deployment
metadata:
  name: erskafka
  namespace: ers 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erskafka
  template:
    metadata:
      labels:
        app: erskafka
    spec:
      containers:
      - image: ghcr.io/dune-daq/pocket-ersdbwriter:latest
        name: erskafka
        envFrom:
        - secretRef:
            name: ers-secret
