apiVersion: apps/v1
kind: Deployment
metadata:
  name: erskafka
  namespace: ers 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erskafka
  template:
    metadata:
      labels:
        app: erskafka
    speci:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.28
        command: ['sh','-c', 'until nslookup kafka-svc.kafka-kraft.svc.cluster.local; do echo waiting for kafka to run; sleep 1; done']
      containers:
      - image: ghcr.io/dune-daq/pocket-ersdbwriter:latest
        name: erskafka
        envFrom:
        - secretRef:
            name: ers-secret
