kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: daqconfig
  name: mongodb-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
roleRef:
  kind: Role
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
