apiVersion: 1

datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: proxy
    orgId: 1
    uid: 'prometheus'
    url:  "http://prometheus-service.monitoring.svc:8080"
    version: 1

  - name: 'ERS'
    type: 'postgres'
    access: proxy
    orgId: 1
    uid: 'ERS'
    url:  "postgres-svc.ers"
    database: "ApplicationDbErrorReporting"
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData: 
      sslmode: 'disable'
    version: 1

  - name: 'influxdb'
    type: 'influxdb'
    access: proxy
    orgId: 1
    uid: 'influxdb'
    url:  "postgres-svc.ers"
    database: "influxdb"
    basicAuth: "true"
    basicAuthUser: "readonly"
    basicAuthPassword: "readonly"
    version: 1

