{
 "title": "DAQ overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SELECT partition FROM public.\"ErrorReports\""
   }
  ]
 },
 "panels": [
  { "title": "Message reporting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Reporting",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time,severity,application_name,issue_name,message,host_name\nFROM public.\"ErrorReports\"\nWHERE partition='${partition}'\nORDER BY -time\n"
    }
   ]
  },
  { "title": "Operational monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Trigger Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Hz" }
   ],
   "targets": [
    {
     "alias": "trigger_rate",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT derivative(td_sent_count, 1s) FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt')",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    }
   ]
  },
  {
   "title": "Trigger & HSI Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "received_tc",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter",
     "select": [
      [
       { "params": [ "tc_received_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "sent_triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_sent_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "inhibited_triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_inhibited_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "paused_triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_paused_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "alias": "total_triggers",
     "measurement": "dunedaq.trigger.moduleleveltriggerinfo.Info",
     "query": "SELECT \"tc_received_count\" FROM \"dunedaq.trigger.moduleleveltriggerinfo.Info\" WHERE (\"source_id\" = '${partition}_trigger.mlt') AND $timeFilter",
     "select": [
      [
       { "params": [ "td_total_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_trigger.mlt" }
     ]
    },
    {
     "measurement": "dunedaq.timinglibs.fakehsieventgeneratorinfo.Info",
     "select": [
      [
       { "params": [ "sent_hsi_events_counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_hsi.fh_sig" }
     ]
    }
   ]
  },
  {
   "title": "Link Handler Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT retry_request FROM \"dunedaq.readout.datalinkhandlerinfo.Info\"",
     "select": [
      [
       { "params": [ "retry_request" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.readout.datalinkhandlerinfo.Info",
     "query": "SELECT request_window_too_old FROM \"dunedaq.readout.datalinkhandlerinfo.Info\"",
     "select": [
      [
       { "params": [ "request_window_too_old" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Builder Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "alias": "avg_ms_for_trigger_record_building",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT average_millisecond_per_trigger FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" \n",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Event Builder Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "loop_counter",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT average_millisecond_per_trigger FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" \n",
     "select": [
      [
       { "params": [ "loop_counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    },
    {
     "alias": "sleep_counter",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT average_millisecond_per_trigger FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" \n",
     "select": [
      [
       { "params": [ "sleep_counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Event Builder Information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "invalid_requests",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT invalid_requests FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\"",
     "select": [
      [
       { "params": [ "invalid_requests" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    },
    {
     "alias": "lost_fragments",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT  lost_fragments FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" ",
     "select": [
      [
       { "params": [ "lost_fragments" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    },
    {
     "alias": "fragments_in_the_book",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT fragments_in_the_book FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" ",
     "select": [
      [
       { "params": [ "fragments_in_the_book" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    },
    {
     "alias": "pending_fragments",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT pending_fragments FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\"",
     "select": [
      [
       { "params": [ "pending_fragments" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    },
    {
     "alias": "pending_trigger_decisions",
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT pending_trigger_decisions FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\"",
     "select": [
      [
       { "params": [ "pending_trigger_decisions" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "${partition}_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Data Writer Information",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Trigger records" }
   ],
   "targets": [
    {
     "alias": "received_trigger_records",
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT \"bytes_output\" FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_dataflow.datawriter') AND $timeFilter",
     "select": [
      [
       { "params": [ "records_received" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "${partition}_dataflow.datawriter"
      }
     ]
    },
    {
     "alias": "written_trigger_records",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT records_written FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = '${partition}_dataflow.datawriter')",
     "select": [
      [
       { "params": [ "records_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "gio_test_dataflow.datawriter" }
     ]
    }
   ]
  },
  {
   "title": "Data Writer Information",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "GBytes written" }
   ],
   "targets": [
    {
     "alias": "written_GB",
     "measurement": "dunedaq.dfmodules.datawriterinfo.Info",
     "query": "SELECT bytes_output/1000000000. FROM \"dunedaq.dfmodules.datawriterinfo.Info\" WHERE (\"source_id\" = 'gio_test_dataflow.datawriter')",
     "select": [
      [
       { "params": [ "bytes_output" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "${partition}_dataflow.datawriter"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues occupancy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT \"number_of_elements\"/\"capacity\" FROM \"dunedaq.appfwk.queueinfo.Info\"  GROUP BY \"source_id\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}