{
 "title": "Frontend",
 "tags": [
  "Subsystem",
  "v2.10.0"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" where $timeFilter"
   }
  ]
 },
 "panels": [
  { "title": "Felix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Felix counters - Blocks with errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_blocks_processed_with_error\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_blocks_processed\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "num_chunks_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": ":{USER}_test_ruflx0.flxcard_1.elink_0_1_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Chunks with errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "generic $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_chunks_processed_with_error\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    },
    {
     "alias": "crc $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_subchunk_crc_errors\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    },
    {
     "alias": "trunc $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_subchunk_trunc_errors\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "num_chunks_processed_with_error"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "felix_test_ruflx0.flxcard_1.elink_0_1_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix counters - Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" }
     ],
     "measurement": "dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo",
     "query": "SELECT sum(\"num_chunks_processed\") FROM \"dunedaq.flxlibs.felixcardreaderinfo.ELinkInfo\" WHERE (\"partition_id\"='${partition}' ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "num_chunks_processed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": ":{USER}_test_ruflx0.flxcard_1.elink_0_1_1"
      }
     ]
    }
   ]
  }
 ]
}