{
 "title": "Network Manager",
 "tags": [
  "v2.10.0",
  "Subsystem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" WHERE $timeFilter"
   },
   {
    "name": "application",
    "label": "Application name",
    "query": "SHOW TAG VALUES FROM \"dunedaq.networkmanager.connectioninfo.Info\" WITH KEY=\"source_id\"  WHERE \"partition_id\"='$partition' AND $timeFilter"
   },
   {
    "name": "connection",
    "label": "Connection name",
    "query": "SHOW TAG VALUES FROM \"dunedaq.networkmanager.connectioninfo.Info\" WITH KEY=\"source_id\"  WHERE \"partition_id\"='$partition' AND $timeFilter"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "SHOW TAG VALUES FROM \"dunedaq.networkmanager.connectioninfo.Info\" WITH KEY=\"source_id\"  WHERE \"partition_id\"='$partition' AND $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sent_bytes\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"sent_bytes\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received_bytes\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"received_bytes\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Relative byte discrepancy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Connections and topics",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_bytes\") - sum(\"sent_bytes\"))/(sum(\"sent_bytes\")+sum(\"received_bytes\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' )  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    },
    {
     "alias": "Connection only",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_bytes\") - sum(\"sent_bytes\"))/(sum(\"sent_bytes\") + sum(\"received_bytes\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.[^.]+\\.[^.]+\\.[^.]+/)  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    },
    {
     "alias": "${connection}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_bytes\") - sum(\"sent_bytes\"))/(sum(\"sent_bytes\")+sum(\"received_bytes\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.[^.]+\\.[^.]+\\.${connection}/)  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Avergage message size - sender side",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT sum(\"sent_bytes\") / sum(\"sent_messages\") FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"sent_messages\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sent_messages\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"sent_messages\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received_messages\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"received_messages\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Relative message discrepancy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Connection and topics",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_messages\") - sum(\"sent_messages\"))/(sum(\"sent_messages\")+sum(\"received_messages\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}')  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    },
    {
     "alias": "Connection only",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_messages\") - sum(\"sent_messages\"))/(sum(\"sent_messages\")+sum(\"received_messages\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.[^.]+\\.[^.]+\\.[^.]+/)  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    },
    {
     "alias": "${connection}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT 2*(sum(\"received_messages\") - sum(\"sent_messages\"))/(sum(\"sent_messages\")+sum(\"received_messages\")) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.[^.]+\\.[^.]+\\.${connection}/)  AND $timeFilter GROUP BY time($__interval)  fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  {
   "title": "Avergage message size - received side",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.networkmanager.nwmgrsentinfo.Info",
     "query": "SELECT sum(\"received_bytes\") / sum(\"received_messages\") FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND \"received_messages\" >0  AND $timeFilter GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda_test" }
     ]
    }
   ]
  },
  { "title": "Application monitors - bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "${application} bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "To $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sent_bytes\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~ /.*\\.${application}\\..*/ AND \"sent_bytes\" > 0 ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "From $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received_bytes\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~ /.*\\.${application}\\..*/ AND \"received_bytes\" > 0 ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  },
  {
   "title": "Application monitors - messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "${application} messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "repeat": "application",
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "To $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sent_messages\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~ /.*\\.${application}\\..*/ AND \"sent_messages\" > 0 ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    },
    {
     "alias": "From $tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "dunedaq.appfwk.queueinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"received_messages\")), 1s) FROM \"dunedaq.networkmanager.connectioninfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~ /.*\\.${application}\\..*/ AND \"received_messages\" > 0 ) AND $timeFilter GROUP BY time($__interval), \"source_id\"",
     "select": [
      [
       { "params": [ "number_of_elements" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "source_id",
       "operator": "=",
       "value": "maroda_test_dataflow.trigger_record_q"
      }
     ]
    }
   ]
  }
 ]
}