---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-ext
  labels:
    app: postgresql
  namespace: ers
spec:
  type: NodePort
  ports:
  - port: 30432
    name: pg-external
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
  selector:
    app: postgresql
