---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-backup 
  namespace: ers
spec:
  selector:
    matchLabels:
      app: postgresql-backup
  template:
    metadata:
      labels:
        app: postgresql-backup
    spec:
      storageClassName: 
      containers:
      - name: postgresql-backup
        image: postgres:12.8
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: ApplicationDbErrorReporting
        envFrom:
        - secretRef:
            name: postgres-secrets
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/
            name: ers-sql
      volumes:
        - name: ers-sql
          configMap:
            name: ers-sql
        - name: "postgresql-pv-backup"
          persistentVolumeClaim:
            claimName: "postgresql-pv-backup-claim"
