---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "postgresql-pv-volume"
  namespace: ers
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  hostPath:
    path: '/scratch/kube/postgres'
  claimRef:
    name: "postgresql-pv-claim"
    namespace: ers

