apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: "postgresql-pv-claim"
  namespace: ers
  labels:
    type: local
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: "postgresql-pv-volume"
  resources:
    requests:
      storage: 1Gi
