---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "postgresql-storage"
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  hostPath:
    path: '/scratch/kube/postgres'
  claimRef:
    name: "postgresql-storage-claim"
    namespace: default

