---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "postgresql-run-pv-volume"
  namespace: microservices
  labels:
    type: local
    app: run-postgres
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 10Gi
  hostPath:
    path: '/scratch/kube/run-postgres'
  claimRef:
    name: "postgresql-run-pv-claim"
    namespace: microservices
---
