apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: "postgresql-run-pv-backup-claim"
  namespace: microservices
  labels:
    type: local
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: "postgresql-run-pv-backup"
  resources:
    requests:
      storage: 1Gi

