---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "postgresql-run-pv-volume"
  namespace: microservices
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
  hostPath:
    path: '/scratch/kube/postgres'
  claimRef:
    name: "postgresql-run-pv-claim"
    namespace: microservices
---
