---
apiVersion: v1
kind: Service
metadata:
  name: postgres-run-svc
  labels:
    app: postgresql
  namespace: microservices 
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
