{
 "title": "Dataflow",
 "description": "Dataflow dashboard",
 "tags": [
  "Subsystem",
  "v3.1.0"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "partition",
    "label": "Partition name",
    "query": "SHOW TAG VALUES WITH KEY=\"partition_id\" where $timeFilter"
   },
   {
    "name": "application",
    "label": "Application name",
    "query": "SHOW TAG VALUES FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WITH KEY=\"source_id\" WHERE $timeFilter AND \"partition_id\"='${partition}'"
   },
   {
    "name": "TRBInstance",
    "label": "TRB name",
    "query": "SHOW TAG VALUES FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WITH KEY=\"source_id\" WHERE $timeFilter AND \"partition_id\"='${partition}'"
   }
  ]
 },
 "panels": [
  { "title": "Partition flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DFO time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Waiting for token",
     "query": "SELECT sum(\"waiting_for_token\") / (sum(\"waiting_for_token\")+sum(\"processing_token\")) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE \"partition_id\"= '$partition' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Processing token",
     "query": "SELECT sum(\"processing_token\") / (sum(\"waiting_for_token\")+sum(\"processing_token\")) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE \"partition_id\"= '$partition' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Forwarding decision",
     "query": "SELECT sum(\"forwarding_decision\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\"))FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE \"partition_id\"= '$partition' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Assignment time",
     "query": "SELECT sum(\"deciding_destination\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\")) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE \"partition_id\"= '$partition' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Waiting for TD",
     "query": "SELECT sum(\"waiting_for_decision\") / (sum(\"waiting_for_decision\")+sum(\"deciding_destination\") + sum(\"forwarding_decision\")) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE \"partition_id\"= '$partition' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "DFO received decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"decisions_received\")), 1s) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "DFO sent decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"decisions_sent\")), 1s) FROM \"dunedaq.dfmodules.datafloworchestratorinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Generated Data requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"generated_data_requests\")), 1s) FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.dataflow[^.]+\\.[^.]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Generated Trigger Records",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"generated_trigger_records\")), 1s) FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.dataflow[^.]+\\.[^.]+/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "generated_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "TDs statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Data Request width",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data_request_width\") / sum(\"generated_data_requests\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.dataflow[^.]+\\.[^.]+/) AND $timeFilter AND \"generated_data_requests\" > 0 GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "average_data_request_width" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Trigger decision width",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"trigger_decision_width\") / sum(\"received_trigger_decisions\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\"=~/[^.]+\\.dataflow[^.]+\\.[^.]+/ ) AND $timeFilter AND \"received_trigger_decisions\" > 0 GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "average_data_request_width" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Pending data",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pending Trigger decisions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"pending_trigger_decisions\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" =~ /${partition}.dataflow[^.]+\\.[^.]+/ AND \"partition_id\"='${partition}') AND (time > now() - 1s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "Pending fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"pending_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" =~ /${partition}.dataflow[^.]+\\.[^.]+/ AND \"partition_id\"='${partition}') AND (time > now() - 1s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "Received Frgments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"fragments_in_the_book\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" =~ /${partition}.dataflow[^.]+\\.[^.]+/ AND \"partition_id\"='${partition}') AND (time > now() - 1s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Event Builder Errors",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lost fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"lost_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\" =~ /[^.]+\\.dataflow[^.]+\\.[^.]+/) AND (time > now() - 1s) ",
     "select": [
      [
       { "params": [ "lost_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"unexpected_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unexpected_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Invalid requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"invalid_requests\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "invalid_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Duplicated TD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"duplicated_trigger_ids\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duplicated_trigger_ids" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Timed out TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"timed_out_trigger_records\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "timed_out_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected TDs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"unexpected_trigger_decisions\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unexpected_trigger_decisions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Abandoned TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT last(\"abandoned_trigger_records\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "abandoned_trigger_records" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "TD Time to complete",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"waiting_time\") / sum(\"completed_trigger_records\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter AND \"completed_trigger_records\" > 0 GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"waiting_time\") / sum(\"completed_trigger_records\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}' ) AND $timeFilter AND \"completed_trigger_records\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Pending TD waiting time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Minimum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT min(\"min_time_since_assignment\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "min_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Maximum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT max(\"max_time_since_assignment\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND  \"outstanding_decisions\" > 0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "$tag_source_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT sum(\"total_time_since_assignment\")/sum(\"outstanding_decisions\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       { "params": [ "total_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    },
    {
     "alias": "Partition average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.dfapplicationinfo.Info",
     "query": "SELECT sum(\"total_time_since_assignment\")/sum(\"outstanding_decisions\") FROM \"dunedaq.dfmodules.dfapplicationinfo.Info\" WHERE (\"partition_id\" = '${partition}') AND $timeFilter AND \"outstanding_decisions\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_time_since_assignment" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition_id", "operator": "=", "value": "maroda" }
     ]
    }
   ]
  },
  {
   "title": "${application} TRB: ${TRBInstance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Event Builder Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Loops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"loop_counter\")), 1s) FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "loop_counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Sleeps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT non_negative_derivative(cumulative_sum(sum(\"sleep_counter\")), 1s) FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sleep_counter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Trigger Building Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Pending fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT distinct(\"pending_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pending_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Received fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT distinct(\"fragments_in_the_book\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fragments_in_the_book" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Pending TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT distinct(\"pending_trigger_decisions\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pending_trigger_decisions" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Event Builder Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Lost fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"lost_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lost_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected fragments",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"unexpected_fragments\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unexpected_fragments" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Invalid requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"invalid_requests\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "invalid_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Duplicated TD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"duplicated_trigger_ids\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duplicated_trigger_ids" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Timed out TR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"timed_out_trigger_records\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "timed_out_trigger_records" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Unexpected TDs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT mean(\"unexpected_trigger_decisions\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unexpected_trigger_decisions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    },
    {
     "alias": "Abandoned TRs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT distinct(\"abandoned_trigger_records\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "abandoned_trigger_records" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  },
  {
   "title": "Event Builders Information",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Time for the TRB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dunedaq.dfmodules.triggerrecordbuilderinfo.Info",
     "query": "SELECT sum(\"data_waiting_time\") / sum(\"generated_trigger_records\") FROM \"dunedaq.dfmodules.triggerrecordbuilderinfo.Info\" WHERE (\"partition_id\" = '${partition}' AND \"source_id\" = '${partition}.${application}.${TRBInstance}') AND $timeFilter AND \"generated_trigger_records\" > 0 GROUP BY time($__interval), \"source_id\" fill(null)",
     "select": [
      [
       {
        "params": [
         "average_millisecond_per_trigger"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source_id", "operator": "=", "value": "maroda_test_dataflow.trb" }
     ]
    }
   ]
  }
 ]
}