apiVersion: apps/v1
kind: Deployment
metadata:
  name: runnumber-rest
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: runnumber-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: runnumber-rest
    spec:
      containers:
      - image: ghcr.io/dune-daq/pocket-runnumber-rest:0.8
        name: runnumber-rest
        envFrom:
        - secretRef:
            name: runnumber-rest-secrets
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: runnumber-rest-svc
  labels:
    app: runnumber-rest
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: runnumber-rest

---
apiVersion: v1
kind: Service
metadata:
  name: runnumber-rest-svc-ext
  labels:
    app: runnumber-rest
  namespace: microservices
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30050
  selector:
    app: runnumber-rest

