---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runregistry-rest
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: runregistry-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: runregistry-rest
    spec:
      initContainers:
      - name: wait-for-run-postgres
        image: busybox:1.28
        command: ['sh','-c', 'until nslookup postgres-run-svc-ext.microservices.svc.cluster.local; do echo waiting for run-postgres to run; sleep 10; done']
      storageClassName:
      containers:
      - name: runregistry-rest
        image: ghcr.io/dune-daq/pocket-runregistry-rest:v0.0.7
        envFrom:
        - secretRef:
            name: runregistry-rest-secrets
        ports:
        - containerPort: 5005
        #   protocol: TCP
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: runregistry-rest-svc-ext
  labels:
    app: runregistry-rest
  namespace: microservices
spec:
  type: NodePort
  ports:
  - port: 30005
    protocol: TCP
    targetPort: 5005
    nodePort: 30005
  selector:
    app: runregistry-rest
