apiVersion: apps/v1
kind: Deployment
metadata:
  name: runregistry-rest
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: runregistry-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: runregistry-rest
    spec:
      #      initContainers:
      #      - name: wait-for-run-postgres
      #        image: busybox:1.28
      #        command: ['sh','-c', 'until nslookup postgres-run-svc.microservices.svc.cluster.local; do echo waiting for run-postgres to run; sleep 1; done']
      containers:
      - image: ghcr.io/dune-daq/pocket-runregistry-rest:v0.0.3
        name: runregistry-rest
        envFrom:
        - secretRef:
            name: runregistry-rest-secrets
        ports:
        - containerPort: 5005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
          #---
          #apiVersion: v1
          #kind: Service
          #metadata:
          #  name: runregistry-rest-svc
          #  labels:
          #    app: runregistry-rest
          #  namespace: microservices
          #spec:
          #  type: ClusterIP
          #  ports:
          #  - port: 5005
          #    protocol: TCP
          #    targetPort: 5005
          #  selector:
          #    app: runregistry-rest
          #
          #---
          #apiVersion: v1
          #kind: Service
          #metadata:
          #  name: runregistry-rest-svc-ext
          #  labels:
          #    app: runregistry-rest
          #  namespace: microservices
          #spec:
          #  type: NodePort
          #  ports:
          #  - port: 5005
          #    protocol: TCP
          #    targetPort: 5005
          #    nodePort: 30005
          #  selector:
          #    app: runregistry-rest
