apiVersion: apps/v1
kind: Deployment
metadata:
  name: runregistry-rest
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: runregistry-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: runregistry-rest
    spec:
      containers:
      - image: ghcr.io/dune-daq/pocket-runregistry-rest:0.8
        name: runregistry-rest
        envFrom:
        - secretRef:
            name: runregistry-rest-secrets
        ports:
        - containerPort: 5005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: runregistry-rest-svc
  labels:
    app: runregistry-rest
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: runregistry-rest

---
apiVersion: v1
kind: Service
metadata:
  name: runregistry-rest-svc-ext
  labels:
    app: runregistry-rest
  namespace: microservices
spec:
  type: NodePort
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
    nodePort: 30005
  selector:
    app: runregistry-rest
